basePath: /api/v1
definitions:
  swagger.DigimonInfo:
    properties:
      id:
        type: string
      name:
        type: string
      status:
        type: string
    type: object
  swagger.ModelError:
    properties:
      code:
        type: number
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Digimon server repo.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths:
  /api/v1/digimons/{digimonId}:
    get:
      consumes:
      - application/json
      description: get digimon by Id
      parameters:
      - description: Digimon Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.DigimonInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ModelError'
      summary: Get Digimon Information
      tags:
      - ""
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
